version: "3"

services:
  front:
    image: 213ogd/front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staticfiles.rule=Host(`front.mohammedkhellafi.me`)"
      - "traefik.http.services.staticfiles.loadbalancer.server.port=80"
      - "traefik.http.routers.staticfiles.entrypoints=websecure"
      - "traefik.http.routers.staticfiles.tls.certresolver=leresolver"
    build:
      context: .
    volumes:
      - ./src:/app/src
    container_name: front
    ports:
      - 3000:80
    networks:
      - ogd
      - web
    environment:
      - REACT_APP_URI=http://back.mohammedkhellafi.me
  back:
    image: 213ogd/server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staticfiles.rule=Host(`back.mohammedkhellafi.me`)"
      - "traefik.http.services.staticfiles.loadbalancer.server.port=80"
      - "traefik.http.routers.staticfiles.entrypoints=websecure"
      - "traefik.http.routers.staticfiles.tls.certresolver=leresolver"
    container_name: server
    ports:
      - 4000:80
    networks:
      - ogd
      - web

networks:
  ogd:
  web:
    external:
      name: web

