version: "3"

services:
  front:
    image: 213ogd/front
    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.front.rule=Host(`front.mohammedkhellafi.me`)"
#      - "traefik.http.services.front.loadbalancer.server.port=80"
#      - "traefik.http.routers.front.entrypoints=websecure"
#      - "traefik.http.routers.front.tls.certresolver=leresolver"
#      - traefik.backend=font
#      - traefik.http.routers.front.tls=true
#      - traefik.http.routers.front.entrypoints=web
#      - traefik.http.routers.front.tls.certresolver=lets-encrypt
#      - traefik.port=3000
      - - traefik.http.routers.front.rule=Host(`front.mohammedkhellafi.me`)" # domain to expose on
      - "traefik.http.routers.front.entrypoints=websecure" # if you named your 443 entrypoint differently than webscure, substitute it here!
      - "traefik.http.routers.front.tls.certresolver=myresolver"
    build:
      context: .
    volumes:
      - ./src:/app/src
    container_name: front
    networks:
      - ogd
      - web
    environment:
      - REACT_APP_URI=http://back.mohammedkhellafi.me
  back:
    image: 213ogd/server
    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.back.rule=Host(`back.mohammedkhellafi.me`)"
#      - "traefik.http.services.back.loadbalancer.server.port=80"
#      - "traefik.http.routers.back.entrypoints=websecure"
#      - "traefik.http.routers.back.tls.certresolver=leresolver"
#      - traefik.backend=back
#      - traefik.http.routers.back.tls=true
#      - traefik.http.routers.back.entrypoints=web
#      - traefik.http.routers.back.tls.certresolver=lets-encrypt
#      - traefik.port=4000
      - "traefik.enable=true"
      - traefik.http.routers.back.rule=Host(`back.mohammedkhellafi.me`)" # domain to expose on
      - "traefik.http.routers.back.entrypoints=websecure" # if you named your 443 entrypoint differently than webscure, substitute it here!
      - "traefik.http.routers.back.tls.certresolver=myresolver"
    container_name: server
    networks:
      - ogd
      - web

networks:
  ogd:
  web:
    external: true


