version: "3"

services:
  front:
    image: 213ogd/front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.entrypoints=http"
      - "traefik.http.routers.front.rule=Host(`front.mohammedkhellafi.me`)"
      - "traefik.http.middlewares.front-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.front-secure.entrypoints=https"
      - "traefik.http.routers.front-secure.rule=Host(`front.mohammedkhellafi.me`)"
      - "traefik.http.routers.front-secure.tls=true"
      - "traefik.http.routers.front-secure.tls.certresolver=http"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    build:
      context: .
    volumes:
      - ./src:/app/src
    container_name: front
    networks:
      - ogd
      - web
    environment:
      - REACT_APP_URI=http://back.mohammedkhellafi.me
  back:
    image: 213ogd/server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.entrypoints=http"
      - "traefik.http.routers.back.rule=Host(`back.mohammedkhellafi.me`)"
      - "traefik.http.middlewares.back-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.back-secure.entrypoints=https"
      - "traefik.http.routers.back-secure.rule=Host(`back.mohammedkhellafi.me`)"
      - "traefik.http.routers.back-secure.tls=true"
      - "traefik.http.routers.front-secure.tls.certresolver=http"
      - "traefik.http.services.back.loadbalancer.server.port=4000"
      - "traefik.docker.network=web"
    container_name: server
    networks:
      - ogd
      - web

networks:
  ogd:
  web:
    external: true


