version: "3"

services:
  front:
    image: 213ogd/front
    labels:
      - traefik.http.routers.front.rule=Host(`front.mohammedkhellafi.me`)
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    container_name: front
    networks:
      - ogd
    environment:
      - REACT_APP_URI=http://mohammedkhellafi.me:4000/
  back:
    image: 213ogd/server
    
    labels:
      - traefik.http.routers.back.rule=Host(`mohammedkhellafi.me`)
    ports:
      - "4000:4000"
    container_name: server
    networks:
      - ogd

networks:
  ogd:
  web:
    external: true
