version: "3"

services:
  front:
    image: 213ogd/front
      - traefik.http.routers.front.rule=Host(`front.mohammedkhellafi.me`)
      - traefik.http.routers.front.tls=true
      - traefik.http.routers.front.tls.certresolver=lets-encrypt
      - traefik.port=80
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    container_name: front
    networks:
      - ogd
      - web
    environment:
      - REACT_APP_URI=http://mohammedkhellafi.me:4000/
  back:
    image: 213ogd/server
    
    labels:
      - traefik.http.routers.back.rule=Host(`mohammedkhellafi.me`)
      - traefik.http.routers.back.tls=true
      - traefik.http.routers.back.tls.certresolver=lets-encrypt
      - traefik.port=80
    ports:
      - "4000:4000"
    container_name: server
    networks:
      - ogd
      - web

networks:
  ogd:
  web:
    external: true
