version: "3"

services:
  front:
    image: 213ogd/front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`front.mohammedkhellafi.me`)"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=leresolver"
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    container_name: front
    networks:
      - ogd
    environment:
      - REACT_APP_URI=http://mohammedkhellafi.me:4000/
  back:
    image: 213ogd/server
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`mohammedkhellafi.me`)"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=leresolver"
    ports:
      - "4000:4000"
    container_name: server
    networks:
      - ogd

networks:
  ogd:
  web:
    external: true
