version: "3.7"
services:
  front:
    image: 213ogd/front
    labels:
      traefik.enable: true
      traefik.http.routers.front.rule: Host(`front.mohammedkhellafi.me`)
      traefik.http.routers.front.entrypoints: websecure
      traefik.http.services.front.loadbalancer.server.port: 3000
      traefik.docker.network: web
      traefik.backend: front
      traefik.port: 80
    build:
      context: .
    volumes:
      - ./src:/app/src
    container_name: front
    networks:
      - ogd
      - web
    environment:
      - REACT_APP_URI=https://back.mohammedkhellafi.me
  back:
    image: 213ogd/server
    labels:
      traefik.enable: true
      traefik.http.routers.back.rule: Host(`back.mohammedkhellafi.me`)
      traefik.http.routers.back.entrypoints: websecure
      traefik.http.services.back.loadbalancer.server.port: 4000
      traefik.docker.network: web
      traefik.backend: back
      traefik.port: 80
    container_name: server
    networks:
      - ogd
      - web

networks:
  ogd:
  web:
    external: true


