name: Deploy CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

   runs-on: self-hosted
   steps:
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
      name: Deploy to Docker
      run: docker-compose up -f docker-compse-deploy.yml -d

