name: Deploy CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_run:
    workflows:
      - Build and push on Docker Hub
    types:
      - completed
      - requested
jobs:
  deploy:

   runs-on: [self-hosted]
   steps:
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
      name: Deploy to dev
      uses: JorgenVatle/docker-compose-deploy@v1.0
      with:
        ssh_user: 'ogd' # optional, user to connect to deploy targets with. Defaults to 'root'
        compose_file: 'docker-compose-deploy.yml' # optional, path/filename of your docker-compose file. Defaults to 'docker-compose.yml'
