name: Deploy Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_run:
    workflows:
      - Build and push on Docker Hub
    types:
      - completed
      - requested
jobs:
  deploy:

  runs-on: [self-hosted]
  steps:
    - uses: actions/checkout@v2
    -
      name: Deploy to staging
      run: PORT=${{ secrets.STAGING_PORT }}