name: test CI

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['14.8.0', '15.4.0']
        os:
          - macos-11.0
          - ubuntu-18.04

    steps:
      -
        name: Setup node with version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
